const images = {
  back: require('../Images/back.png'),
  currentLocation: require('../Images/currentLocation.png'),
  currentLocation2: require('../Images/currentLocation2.png'),
  event1: require('../Images/event1.png'),
  event1Card: require('../Images/event1Card.png'),
  event1Pic: require('../Images/event1Pic.png'),
  event2: require('../Images/event2.png'),
  event2Card: require('../Images/event2Card.png'),  
  event2Pic: require('../Images/event2Pic.jpg'),
  event3: require('../Images/event3.png'),
  event3Card: require('../Images/event3Card.png'),
  event3Pic: require('../Images/event3Pic.png'),
  female: require('../Images/female.png'),
  filterEvents: require('../Images/filter-events.png'),
  filterFriends: require('../Images/filter-friends.png'),
  filterRallies: require('../Images/filter-rallies.png'),
  logo: require('../Images/logo.png'),
  male: require('../Images/male.png'),
  messages: require('../Images/messages.png'),
  messagesFilled: require('../Images/messages-filled.png'),
  profile: require('../Images/profile.png'),
  profileFilled: require('../Images/profile_filled.png'),
  rally: require('../Images/logo_filled.png'),
  yourImage: require('../Images/yourImage.png'),
}

export default images
