const images = {
  check: require('../Images/bluecheck.png'),
  currentLocation: require('../Images/currentLocation.png'),
  currentLocation2: require('../Images/currentLocation2.png'),
  event1: require('../Images/event1.png'),
  event1Card: require('../Images/event1Card.png'),
  event1Pic: require('../Images/event1Pic.png'),
  event2: require('../Images/event2.png'),
  event2Card: require('../Images/event2Card.png'),
  event2Pic: require('../Images/event2Pic.jpg'),
  event3: require('../Images/event3.png'),
  event3Card: require('../Images/event3Card.png'),
  event3Pic: require('../Images/event3Pic.png'),
  filterEvents: require('../Images/filter-events.png'),
  filterFriends: require('../Images/filter-friends.png'),
  filterRallies: require('../Images/filter-rallies.png'),
  friend1: require('../Images/friend1.png'),
  friend2: require('../Images/friend2.png'),
  rally: require('../Images/rally_text.png'),
  rally1: require('../Images/rally2.png'),
  rally2: require('../Images/rally1.png'),
  yourImage: require('../Images/yourImage.png'),
}

export default images
